name: counter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  ## App Packages ##

  # State management
  get: ^4.6.6

  # Local storage
  hive: ^2.2.3
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3

  # Responsive
  responsive_sizer: ^3.3.1
  auto_size_text: ^3.0.0

  # Device info
  device_info_plus: ^10.1.0

  # Permission
  permission_handler: ^11.3.1

  # Bluetooth
  flutter_blue_plus: ^1.32.8

  # Localization & date
  intl: ^0.19.0

  # Translations
  easy_localization: ^3.0.7

  # Animation image
  lottie: ^3.1.2

  # Dart
  rxdart: ^0.27.7

  # Picker number
  numberpicker: ^2.1.2

  # Loading
  flutter_spinkit: ^5.2.1

  # Images
  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2

  # Animation
  animated_text_kit: ^4.2.2
  page_transition: ^2.1.0
  flutter_staggered_animations: ^1.1.1

  # Grid View
  flutter_staggered_grid_view: ^0.7.0

  # Neumporphic
  clay_containers: ^0.3.4

  # Remote API
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application :
  assets:
    - assets/jsons/
    - assets/languages/
    - assets/svgs/